{
  "buildCommand": "cd spazio-backend && npm install",
  "startCommand": "cd spazio-backend && npx ts-node --project . src/main/server.ts",
  "healthcheckPath": "/",
  "healthcheckInterval": 30,
  "region": "sao-paulo"
}
