services:
  - type: web
    name: spazio-backend
    env: node
    region: oregon
    rootDir: spazio-backend
    buildCommand: npm install && npx prisma generate --schema=./prisma/schema.prisma && npx tsc
    startCommand: node dist/main/server.js
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: DATABASE_URL
        value: "" # Adicione sua URL do PostgreSQL aqui
      - key: JWT_SECRET
        value: "" # Adicione uma chave secreta aqui
      - key: FRONTEND_URL
        value: "" # URL do seu frontend na Vercel
      - key: PORT
        value: "3001"